import { test, expect } from '../../apps/web/node_modules/@playwright/test/index.mjs';
import { outputDirectory } from './paths';
import { resolve } from 'node:path';
const root = resolve(import.meta.dirname, '../..');
test('real Compose PDF upload persists across browser reload and metadata changes', async ({ page }) => {
  test.skip(process.env.LIBRARY_LIVE_E2E !== '1', 'Enable only against the designated local acceptance instance. No provider calls.');
  test.setTimeout(90000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:8080/#/upload');
  await page.locator('input[type=file]').setInputFiles(resolve(root, 'fixtures/sample.pdf'));
  await page.getByRole('button', { name: '保存 PDF 原件', exact: true }).click();
  const duplicate = page.getByRole('button', { name: '建立独立文档' });
  const saved = page.getByRole('link', { name: '原件已保存 · 管理文档' });
  await expect(duplicate.or(saved)).toBeVisible({ timeout: 60000 });
  if (await duplicate.isVisible()) await duplicate.click();
  await saved.click();
  await expect(page.getByRole('heading', { name: '原件', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '编辑题名与标签' }).click();
  const uniqueTitle = `Agent acceptance ${Date.now()}`;
  await page.getByLabel('题名', { exact: true }).fill(uniqueTitle);
  await page.getByLabel('标签（逗号分隔）').fill('agent-acceptance, PDF');
  await page.getByRole('button', { name: '保存目录信息', exact: true }).click();
  await expect(page.getByRole('heading', { name: uniqueTitle, exact: true })).toBeVisible();
  await page.getByRole('button', { name: '收藏', exact: true }).click();
  await expect(page.getByRole('button', { name: '取消收藏', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: uniqueTitle, exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '取消收藏', exact: true })).toBeVisible();
  await expect(page.getByText('agent-acceptance · PDF')).toBeVisible();
  const pdf = await page.request.get(await page.getByRole('link', { name: '打开原 PDF', exact: true }).getAttribute('href')!);
  expect(pdf.status()).toBe(200);
  const source = await import('node:fs/promises').then(fs => fs.readFile(resolve(root, 'fixtures/sample.pdf')));
  expect(await pdf.body()).toEqual(source);
  await page.screenshot({ path: resolve(outputDirectory('live'), 'live-document-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: resolve(outputDirectory('live'), 'live-document-mobile.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: '归档文档', exact: true }).click();
  await expect(page.getByRole('button', { name: '取消归档', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: '取消归档', exact: true })).toBeVisible();
  expect(errors).toEqual([]);
  // Keep the clearly marked, archived acceptance record for evidence; no deletion or model call.
});
