import {test, expect} from '../../src/apps/web/node_modules/@playwright/test/index.mjs';
import { inputPath } from './paths';
import {pathToFileURL} from 'node:url';
import {writeFile} from 'node:fs/promises';

test('actual worker unfinished-draft export remains labelled and usable under file offline', async ({page, context}, testInfo) => {
  const supplied = process.env.LIBRARY_DRAFT_HTML;
  test.skip(!supplied, 'Requires an independently generated actual API -> worker draft HTML.');
  const file = inputPath(supplied!);
  const requests: string[] = [];
  const errors: string[] = [];
  page.on('request', request => {if (/^https?:/.test(request.url())) requests.push(request.url());});
  page.on('pageerror', error => errors.push(error.message));
  await context.setOffline(true);
  await page.goto(pathToFileURL(file).href);
  await expect(page.getByText('DRAFT — 未完成草稿，缺失 1 块译文', {exact: true})).toBeVisible();
  await expect(page.getByText('DRAFT — 此块译文未完成', {exact: true})).toBeVisible();
  await expect(page.locator('#b-item [data-language=source]')).toBeVisible();
  await expect(page.locator('#b-item [data-language=source]')).toContainText('Keep the original.');
  await expect(page.getByText('Later target sentinel')).toHaveCount(0);
  await expect(page.locator('a[href*="/api/"]')).toHaveCount(0);
  await expect(page.locator('img').first()).toHaveJSProperty('naturalWidth', 360);
  await page.screenshot({path: testInfo.outputPath('draft-offline-desktop.png'), fullPage: true});
  await page.getByRole('button', {name: '译文', exact: true}).click();
  await expect(page.getByText('DRAFT — 此块译文未完成', {exact: true})).toBeVisible();
  await expect(page.locator('#b-item [data-language=source]')).not.toBeVisible();
  await page.getByRole('button', {name: '双语', exact: true}).click();
  await page.getByRole('link', {name: '注释', exact: true}).click();
  await expect(page).toHaveURL(/#b-fn1$/);
  await page.getByRole('link', {name: '返回引用位置', exact: true}).click();
  await expect(page).toHaveURL(/#b-p2$/);
  await page.setViewportSize({width: 390, height: 844});
  await page.evaluate(() => scrollTo(0, 0));
  const width = await page.evaluate(() => ({scroll: document.documentElement.scrollWidth, viewport: innerWidth}));
  expect(width.scroll).toBeLessThanOrEqual(width.viewport);
  await page.screenshot({path: testInfo.outputPath('draft-offline-mobile.png'), fullPage: true});
  expect(requests).toEqual([]);
  expect(errors).toEqual([]);
  await writeFile(testInfo.outputPath('browser-review.json'), JSON.stringify({file, scheme: 'file', offline: true, draft_banner: true, missing_blocks: 1, source_preserved: true, later_edit_absent: true, footnote_roundtrip: true, desktop_width: 1440, mobile_width: 390, horizontal_overflow: false, network_requests: requests, page_errors: errors}, null, 2));
});
