let selectedFiles=[],filter={q:'',language:'all',starred:false},selectedJobId=null,toastTimer=null;
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.hidden=true,5000);}
function route(){return (location.hash.replace(/^#\/?/,'')||'library').split('/');}
function navigate(r){if(location.hash==='#/'+r)render();else location.hash='/'+r;}
function pageHead(title,text,action=''){return `<div class="page-head"><div><h1>${title}</h1><p>${text}</p></div>${action}</div>`;}
function sidebar(view){const links=[['library','library','文档库'],['import','upload','上传 PDF'],['jobs','tasks','翻译任务'],['glossary','glossary','术语表'],['settings','settings','设置'],['architecture','architecture','架构与交付']];return `<aside class="sidebar" id="sidebar"><button class="icon-btn mobile-close" data-action="menu" aria-label="关闭导航">${icon('close')}</button><div class="brand"><span class="brand-icon">${icon('book')}</span><div>对照文库<small>BILINGUAL LIBRARY</small></div></div><div class="nav-label">个人知识库</div><nav aria-label="主导航">${links.map(([r,i,t])=>`<a href="#/${r}" class="nav-item" ${view===r?'aria-current="page"':''}>${icon(i)}${t}${r==='library'?`<span class="count">${state.documents.length}</span>`:''}</a>`).join('')}</nav><div class="side-bottom"><strong>个人 PDF 版 · v3</strong><p>无需账户，打开即用。<br>演示状态保存在当前浏览器。</p><button class="btn sm ghost" data-action="scope">原型能力边界 ${icon('arrow')}</button></div></aside>`;}
function render(){const[v,id]=route();document.documentElement.dataset.theme=state.theme;let content;
 if(v==='library')content=libraryView();else if(v==='import')content=importView();else if(v==='jobs')content=jobsView(id);else if(v==='review')content=reviewView(id);else if(v==='reader')content=readerView(id);else if(v==='edit')content=editView(id);else if(v==='history')content=historyView(id);else if(v==='glossary')content=glossaryView();else if(v==='settings')content=settingsView();else if(v==='architecture')content=architectureView();else content=pageHead('页面不存在','返回文档库继续浏览。');
 const names={library:'文档库',import:'上传 PDF',jobs:'翻译任务',review:'校对',reader:'静态阅读',edit:'译文修订',history:'版本历史',glossary:'术语表',settings:'设置',architecture:'架构与交付'};
 document.querySelector('#app').innerHTML=`${sidebar(['reader','edit','history'].includes(v)?'library':v==='review'?'jobs':v)}<div class="shell"><header class="topbar"><div class="stack"><button class="icon-btn mobile-menu" data-action="menu" aria-label="打开导航">${icon('menu')}</button><div class="breadcrumb">个人知识库 <span style="margin:0 12px">/</span> ${names[v]||''}</div></div><div class="stack"><span class="demo-chip">交互原型 · 不调用模型</span><button class="icon-btn" data-action="theme" aria-label="切换明暗主题">${icon('moon')}</button></div></header><main class="main" id="main">${content}<footer class="footer-app"><span>仅 PDF · 静态阅读 · reader-v1</span><span>${storageAvailable?'当前浏览器演示状态':'当前为内存演示模式'}</span></footer></main></div>`;bind(v,id);}
function libraryView(){return pageHead('文档库','把 PDF 留下来，以熟悉的双语方式慢慢读。',`<a class="btn primary" href="#/import">${icon('plus')}上传 PDF</a>`)+`<div class="tools"><label class="searchbox">${icon('search')}<input id="library-search" type="search" aria-label="搜索文档" placeholder="搜索标题或标签…" value="${esc(filter.q)}"></label><select id="language-filter" aria-label="目标语言"><option value="all">全部语言</option>${languageOptions(filter.language)}</select><button class="icon-btn ${filter.starred?'active':''}" data-action="filter-stars" aria-label="仅显示收藏">${icon('star')}</button></div><p class="muted" id="result-count"></p><div class="library-grid" id="library-grid"></div><div class="hint-band">${icon('book',true)}<p><strong>阅读页始终是一份独立文件。</strong><br>原有论文样式保持不变；已导出的文章不依赖翻译服务。</p><a href="../index.html">完整 Spec / Plan ${icon('arrow')}</a></div>`;}
function updateLibrary(){const docs=state.documents.filter(d=>(!filter.starred||d.starred)&&(filter.language==='all'||d.language===filter.language)&&(`${d.title} ${d.titleZh||''} ${d.tags.join(' ')}`).toLowerCase().includes(filter.q.toLowerCase()));document.querySelector('#result-count').textContent=`${docs.length} 篇文档 · ${state.documents.filter(x=>x.kind!=='source_only').length} 个阅读版本`;document.querySelector('#library-grid').innerHTML=docs.length?docs.map(card).join(''):'<div class="empty"><h2>没有找到文档</h2><button class="btn" data-action="clear-filter">清除筛选</button></div>';}
function card(d){const pending=d.kind==='source_only';const src=d.snippet||d.blocks?.[0]?.source||'PDF 原件条目 · 仅记录浏览器本地选择的信息。';const dst=d.snippetZh||d.blocks?.[0]?.target||'尚未解析与翻译。刷新后需重新选择本地文件才能预览原件。';return `<article class="doc-card"><div class="doc-top"><span class="pill ${pending||d.kind==='demo'?'warn':'ready'}">${pending?'原件条目 · 浏览器演示':d.kind==='demo'?'已发布 · 流程样例':'既有译读版'}</span><button class="icon-btn ${d.starred?'active':''}" data-action="star" data-id="${d.id}" aria-label="收藏 ${esc(d.title)}">${icon('star')}</button></div><div class="doc-main"><h2>${esc(d.title)}</h2><div class="doc-zh">${esc(d.titleZh||'PDF 原件，尚无译文')}</div><div class="mini-reader"><div class="orig">${esc(src.slice(0,145))}${src.length>145?'…':''}</div><div class="trans">${esc(dst.slice(0,115))}${dst.length>115?'…':''}</div></div><div class="doc-meta"><span>PDF${d.pages?' · '+d.pages+' 页':''}</span><span>${pending?'待翻译':LANGS[d.language]+' · '+d.pairs+' 组段落'}</span></div><div class="stack" style="margin-top:14px">${d.tags.map(t=>`<span class="pill muted">${esc(t)}</span>`).join('')}</div></div><div class="doc-footer">${pending?`<button class="btn primary" data-action="start-demo" data-id="${d.id}">演示翻译流程</button>`:`<a class="btn primary" href="#/reader/${d.id}">${icon('book')}开始阅读</a>`}<div class="stack"><button class="icon-btn" data-action="details" data-id="${d.id}" aria-label="详情">${icon('info')}</button>${!pending?`<button class="icon-btn" data-action="export" data-id="${d.id}" aria-label="导出静态网页">${icon('download')}</button>`:''}</div></div></article>`;}
function importView(){return pageHead('上传 PDF','只接收 PDF，所有译文继续发布为同样风格的静态网页。')+`<div class="split"><section class="panel"><form id="pdf-form"><label class="dropzone" id="dropzone" tabindex="0" role="button" aria-label="选择 PDF 文件"><input type="file" id="file-input" class="hidden" multiple accept=".pdf,application/pdf">${icon('upload',true)}<strong>拖入 PDF，或点击选择</strong><small>仅 PDF · 最多 10 份 · 每份上限 50 MiB</small></label><div id="selected-files" style="margin:18px 0"></div><div class="two-cols"><div class="field"><label for="source-language">原文语言</label><select id="source-language" style="width:100%"><option value="auto">自动识别（正式后端）</option><option value="en">English</option><option value="zh-Hans">简体中文</option></select></div><div class="field"><label for="target-language">目标语言</label><select id="target-language" style="width:100%">${languageOptions(state.defaults.language)}</select></div></div><div class="field"><label>阅读模板</label><div class="input stack between"><span>当前双语论文样式</span><span class="pill ready">reader-v1 · 固定模板</span></div></div><div class="field-note warn"><strong>当前是原型。</strong>仅在浏览器检查扩展名、大小和 PDF 文件头；不向服务器上传、不验证完整PDF、不提取或翻译正文。文件条目与正式后端持久保存不同。</div><p id="upload-error" class="error" role="alert"></p><button class="btn primary" id="add-pdfs" type="submit">加入原型文档库 ${icon('arrow')}</button></form></section><aside><section class="panel"><h2 style="margin-top:0">从 PDF 到静态阅读页</h2><div class="mini-reader"><div class="orig">Each source paragraph is paired with its translation.</div><div class="trans">每个原文段落都与其译文成对呈现。</div></div><ol class="flow-list"><li><strong>保存原件</strong><small>PDF 字节与内容哈希</small></li><li><strong>结构预检</strong><small>页码、段落、图表和未解决区域</small></li><li><strong>逐段翻译与校验</strong><small>外发确认、预算与断点恢复</small></li><li><strong>静态发布</strong><small>固定模板，不需要运行时翻译</small></li></ol></section><div class="field-note" style="margin-top:20px">M1–M2 认证文本型 PDF。扫描正文将提示 OCR_REQUIRED，不跳过后冒充全文完成。没有其他文件或粘贴导入入口。</div></aside></div>`;}
async function chooseFiles(list){if(list.length>10){toast('一次最多选择10份PDF。');return;}selectedFiles=[];for(const f of list){let error='';if(!/\.pdf$/i.test(f.name))error='只支持 .pdf 文件';else if(f.size>50*1024*1024)error='超过50 MiB';else if(f.size<5)error='不是有效PDF文件头';else{try{const head=new TextDecoder('latin1').decode(await f.slice(0,1024).arrayBuffer());if(!head.includes('%PDF-'))error='未找到PDF文件头（伪装文件）';}catch{error='无法读取本地文件';}}selectedFiles.push({file:f,error});}showFiles();}
function showFiles(){const e=document.querySelector('#selected-files');if(!e)return;e.innerHTML=selectedFiles.map(x=>`<div class="file-result"><strong>${esc(x.file.name)}</strong><small class="${x.error?'error':'muted'}">${x.error?esc(x.error):`${(x.file.size/1048576).toFixed(2)} MiB · 初筛通过，未上传`}</small></div>`).join('');}
function jobsView(id){const current=getJob(id||selectedJobId)||state.jobs[0];return pageHead('翻译任务','阶段状态、预检、校对和发布保持分离。',`<button class="btn" data-action="sample-job">创建校对演示</button>`)+`<div class="field-note warn" style="margin-bottom:24px">所有任务阶段均为模拟。演示使用固定 3 段样本，不是所选 PDF 的内容；模型调用与费用都是 0。</div>${state.jobs.length?`<div class="job-list">${state.jobs.map(j=>`<button class="job-row ${current?.id===j.id?'selected':''}" data-action="select-job" data-id="${j.id}">${icon('file')}<span class="job-info"><strong>${esc(j.origin)}</strong><small>PDF → ${LANGS[j.language]} · 固定流程样例</small></span><span class="pill ${j.status==='needs_review'?'warn':''}">${jobLabel(j)}</span></button>`).join('')}</div>${jobDetail(current)}`:'<section class="empty"><h2>还没有任务</h2><p>上传PDF建立原件条目，或使用上方固定样例体验校对。</p></section>'}`;}
function jobDetail(j){return `<section class="panel"><div class="stack between"><h2 style="margin:0">${esc(j.origin)}</h2><span class="pill">${jobLabel(j)} · 演示</span></div><div class="stage-track">${STAGES.map((s,i)=>`<div class="stage ${j.step>i?'done':j.step===i?'current':''}"><div class="rail"></div>${s}</div>`).join('')}</div>${j.status==='preflight'?`<div class="field-note"><strong>结构预检 · 固定样例</strong><p>样本3段 / 未解决正文0 / 图表0。真实文件页数和内容尚未读取。正式版本会在此显示原PDF覆盖报告与费用估算。</p><label class="check"><input id="preflight-confirm" type="checkbox">我知道接下来处理的是演示样本，不是上传PDF的译文</label><button class="btn primary" data-action="confirm-preflight" data-id="${j.id}">确认并继续演示</button></div>`:''}<dl class="kv"><dt>阅读模板</dt><dd>reader-v1</dd><dt>内容</dt><dd>固定三段；没有提取 ${esc(j.origin)} 正文</dd><dt>模型调用 / 费用</dt><dd>0 次 / 0（没有外发）</dd><dt>术语快照</dt><dd>v${j.glossaryVersion} · 演示</dd></dl><div class="stack" style="margin:20px 0">${['queued','running'].includes(j.status)?`<button class="btn primary" data-action="advance" data-id="${j.id}">推进下一步</button>`:''}${j.status==='needs_review'?`<a class="btn primary" href="#/review/${j.id}">校对问题段落</a>`:''}${j.status==='ready'?`<button class="btn primary" data-action="publish" data-id="${j.id}">发布带说明的样例</button>`:''}${j.status==='published'?`<a class="btn primary" href="#/reader/${j.docId}">阅读样例</a>`:''}${isActive(j)&&j.status!=='paused'?`<button class="btn" data-action="pause" data-id="${j.id}">暂停</button>`:''}${j.status==='paused'?`<button class="btn" data-action="resume" data-id="${j.id}">恢复</button>`:''}${isActive(j)?`<button class="btn danger" data-action="cancel" data-id="${j.id}">取消</button>`:''}</div><div class="log">${j.log.map(l=>`<p>${esc(typeof l==='string'?l:(l.text||l.message||JSON.stringify(l)))}</p>`).join('')}</div></section>`;}
function reviewView(id){const j=getJob(id);if(!j||j.status!=='needs_review')return pageHead('没有待处理问题','从任务列表进入校对。');return pageHead('校对问题段落','只修改译文。示例中的数字错误会阻止发布。',`<a class="btn" href="#/jobs/${j.id}">返回任务</a>`)+`<div class="field-note warn">固定流程样例 · 没有上传PDF的逐块定位，不能把它当作真实原件证据。</div><section class="panel" style="margin-top:24px"><div class="mini-reader"><div class="orig">${esc(demoSource[1])}</div></div><label for="review-text">译文</label><textarea id="review-text" rows="5">${esc(j.translation)}</textarea><p id="review-error" class="error">保护数字应为64，不能写成32。</p><div class="stack"><button class="btn" data-action="fix-example" data-id="${j.id}">填入正确示例</button><button class="btn primary" data-action="save-review" data-id="${j.id}">保存并重验</button></div></section>`;}
function readerView(id){const d=getDoc(id);if(!d)return pageHead('文档不存在','返回文档库。');if(d.kind==='source_only')return pageHead('尚无译文','原型不会把示例内容当作该PDF的翻译。');return pageHead(d.title,d.kind==='legacy'?'原有静态阅读页面，保留旧版说明。':'演示静态内容，不是上传PDF译文。',`<div class="stack"><button class="btn" data-action="export" data-id="${d.id}">${icon('download')}导出</button>${d.kind==='demo'?`<a class="btn" href="#/edit/${d.id}">修订样例</a><a class="btn" href="#/history/${d.id}">历史</a>`:''}</div>`)+`<div class="reader-frame-wrap"><iframe id="reader-frame" class="reader-frame" title="双语静态阅读页面" sandbox="allow-scripts allow-same-origin allow-popups allow-downloads"></iframe></div>`;}
function editView(id){const d=getDoc(id);if(!d||d.kind!=='demo')return pageHead('旧资料不直接重译','请创建固定流程样例体验修订；正式新版本需要从原PDF解析。');return pageHead('局部修订','示例只编辑第二段；其他段落保持不变。保存不会自动发布。',`<a class="btn" href="#/reader/${d.id}">返回阅读</a>`)+`<section class="panel"><p class="field-note warn">M2 前端交互演示：没有调用模型；候选来自内置已知样本。</p><div class="mini-reader"><div class="orig">${esc(d.blocks[1].source)}</div></div><label for="segment-editor">当前译文</label><textarea id="segment-editor" rows="5">${esc(d.draft?.target||d.blocks[1].target)}</textarea><div class="stack" style="margin:20px 0"><button class="btn" data-action="save-draft" data-id="${d.id}">保存草稿</button><button class="btn" data-action="candidate" data-id="${d.id}">生成示例候选</button><button class="btn primary" data-action="publish-draft" data-id="${d.id}">校验并发布修订</button></div>${d.draft?'<p class="muted">已有草稿 · 尚未发布 · 未人工确认</p>':''}${d.candidate?`<div class="field-note"><strong>候选译文 · 未接受</strong><p>${esc(d.candidate.target)}</p><button class="btn" data-action="accept-candidate" data-id="${d.id}">接受到草稿</button></div>`:''}<p>版本检查保留：候选的基准改变时拒绝覆盖；没有账号、团队或协作编辑。</p></section>`;}
function historyView(id){const d=getDoc(id);if(!d||d.kind!=='demo')return pageHead('没有演示历史','旧文章字节不会通过此入口改变。');return pageHead('版本历史',`当前 r${d.revision} · 发布 generation ${d.generation}。回滚只切换当前版本。`,`<a class="btn" href="#/reader/${d.id}">返回阅读</a>`)+`<section class="panel">${[...d.history].reverse().map(h=>`<div class="history-row"><div><strong>修订 r${h.revision}${h.revision===d.revision?' · 当前':''}</strong><p class="muted">${esc(h.reason)} · ${fmtDate(h.time)}</p></div><button class="btn" data-action="rollback" data-id="${d.id}" data-revision="${h.revision}" ${d.revision===h.revision?'disabled':''}>设为当前版本</button></div>`).join('')}</section>`;}
function glossaryView(){return pageHead('术语表',`个人全库术语 · 修订 v${state.glossaryVersion}。修改不自动重写已发表文章。`)+`<section class="panel"><form id="term-form"><div class="two-cols"><div class="field"><label for="term-source">源词项</label><input class="input" id="term-source" maxlength="200" required></div><div class="field"><label for="term-target">推荐译法</label><input class="input" id="term-target" maxlength="200" required></div></div><button class="btn primary">添加术语</button></form><div class="table-wrap"><table><thead><tr><th>源词项</th><th>译法</th><th>操作</th></tr></thead><tbody>${state.glossary.map(t=>`<tr><td>${esc(t.source)}</td><td>${esc(t.target)}</td><td><button class="btn sm" data-action="delete-term" data-id="${t.id}">删除</button></td></tr>`).join('')}</tbody></table></div><p class="muted">实际Provider使用术语及影响分析属于正式M2实现。当前仅验证个人术语的界面与本地状态。</p></section>`;}
function settingsView(){return pageHead('设置','只保留个人偏好、翻译连接状态和部署说明。')+`<div class="split"><section class="panel"><h2>阅读与翻译偏好</h2><form id="settings-form"><div class="field"><label for="default-language">默认目标语言</label><select id="default-language">${languageOptions(state.defaults.language)}</select></div><button class="btn primary">保存偏好</button></form><h2>翻译连接</h2><div class="field-note">原型未连接模型。正式版本从Compose secret读取API key；页面不接收、不保存或回显真实密钥。</div><p class="muted">修改模型与费率后，正式新任务需要重新确认外发范围和预算。</p></section><section class="panel"><h2>Docker Compose</h2><p>宿主只需 Docker 与 Compose。本包根目录 Compose 启动演示网页，不包含已实现的生产翻译服务。</p><pre>docker compose up --build -d</pre><p>默认端口 <code>127.0.0.1:8080</code>。本产品没有登录；请自行控制实例的可达范围。</p><p>应用直接提供HTTP；反代由使用者独立配置，交付包不包含反代服务。</p><a class="btn" href="../html/compose-contract.html">查看正式部署契约</a><hr><button class="btn danger" data-action="reset">恢复原型示例</button></section></div>`;}
function architectureView(){return pageHead('架构与交付','个人 PDF 文档库：动态生产，静态阅读。')+`<section class="panel"><pre>PDF 上传 → 原件保存 → 解析与预检
                        ↓
                 确认外发与预算
                        ↓
              翻译 → 校验 → 校对
                        ↓
              封存 → 固定模板 → 发布
                        ↓
              静态 HTML / 离线阅读</pre><div class="stack"><a class="btn primary" href="../index.html">完整 Spec / Plan</a><a class="btn" href="../html/baseline.html">产品基线</a><a class="btn" href="../html/compose-contract.html">Compose 与依赖</a></div><p>常驻服务：app、worker、parser、PostgreSQL。app直接提供前端、API与静态文件；parser断网并使用本地模型资产。</p><p>不包含其他输入格式、身份登录、成员/角色/权限、分享管理或反代配置。</p></section>`;}
function dialog(title,body,buttons='<button class="btn" data-action="close-dialog">关闭</button>'){const el=document.querySelector('#dialog');el.innerHTML=`<div class="dialog-inner"><h2>${esc(title)}</h2>${body}<div class="stack" style="margin-top:24px">${buttons}</div></div>`;el.showModal();}
function bind(v,id){if(v==='library'){updateLibrary();document.querySelector('#library-search').oninput=e=>{filter.q=e.target.value;updateLibrary();};document.querySelector('#language-filter').onchange=e=>{filter.language=e.target.value;updateLibrary();};}
 if(v==='import'){showFiles();const inp=document.querySelector('#file-input'),drop=document.querySelector('#dropzone');inp.onchange=e=>chooseFiles([...e.target.files]);drop.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();inp.click();}};drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging');};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');chooseFiles([...e.dataTransfer.files]);};document.querySelector('#pdf-form').onsubmit=e=>{e.preventDefault();const good=selectedFiles.filter(x=>!x.error);if(!good.length){document.querySelector('#upload-error').textContent='请先选择至少一份初筛通过的PDF。';return;}const language=document.querySelector('#target-language').value;for(const x of good){const id=uuid();state.documents.unshift({id,title:x.file.name,kind:'source_only',source:'PDF',language,pairs:0,tags:['待翻译'],createdAt:new Date().toISOString(),starred:false,size:x.file.size});originalFiles.set(id,URL.createObjectURL(x.file));}save();selectedFiles=[];navigate('library');toast('已记录本地PDF选择信息；未上传到服务器，未执行翻译。');};}
 if(v==='reader'){const d=getDoc(id),frame=document.querySelector('#reader-frame');if(frame&&d){if(d.kind==='legacy')frame.src='reader/'+d.filename;else frame.srcdoc=staticReader(d);}}
 if(v==='glossary')document.querySelector('#term-form').onsubmit=e=>{e.preventDefault();const source=document.querySelector('#term-source').value.trim(),target=document.querySelector('#term-target').value.trim();if(!source||!target)return;state.glossary.push({id:uuid(),source,target,note:''});state.glossaryVersion++;save();render();};
 if(v==='settings')document.querySelector('#settings-form').onsubmit=e=>{e.preventDefault();state.defaults.language=document.querySelector('#default-language').value;save();toast('已保存当前浏览器的个人偏好。');};}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id,d=getDoc(id),j=getJob(id);
 if(a==='theme'){state.theme=state.theme==='dark'?'light':'dark';save();render();}
 else if(a==='menu')document.querySelector('#sidebar').classList.toggle('open');
 else if(a==='filter-stars'){filter.starred=!filter.starred;render();}
 else if(a==='clear-filter'){filter={q:'',language:'all',starred:false};render();}
 else if(a==='star'&&d){d.starred=!d.starred;save();render();}
 else if(a==='details'&&d)dialog(d.title,`<p>来源：PDF · ${d.kind==='source_only'?'原型元数据条目，原件未保存到服务器':'固定版本'}</p><p>${esc(d.note||'原有译读页面保留原来的整理说明，不伪造精确来源。')}</p>${d.kind==='source_only'?(originalFiles.has(id)?`<a class="btn" href="${originalFiles.get(id)}" target="_blank" rel="noopener">预览已选本地 PDF</a>`:'<p>刷新后本地文件引用失效，请重新选择PDF；正式版由服务端持久保存。</p>'):`<a class="btn" href="#/reader/${id}" data-action="close-dialog">开始阅读</a>`}`);
 else if(a==='export'&&d)exportDoc(d);
 else if(a==='start-demo'&&d){const x=newJob(d.title,d.language,true,d.id);selectedJobId=x.id;navigate('jobs/'+x.id);}
 else if(a==='sample-job'){const x=newJob('待校对示例.pdf',state.defaults.language,true);x.step=5;x.status='needs_review';x.translation=x.translation.replace('64','32');save();navigate('review/'+x.id);}
 else if(a==='select-job'){selectedJobId=id;navigate('jobs/'+id);}
 else if(a==='advance'&&j)advanceJob(j);
 else if(a==='confirm-preflight'&&j){if(!document.querySelector('#preflight-confirm').checked){toast('请先确认这是固定演示样本。');return;}j.confirmed=true;j.step=3;j.status='running';logJob(j,'明确确认演示；没有外发。');save();render();}
 else if(a==='pause'&&j){j.previousStatus=j.status;j.status='paused';save();render();}
 else if(a==='resume'&&j){j.status=j.previousStatus||'running';save();render();}
 else if(a==='cancel'&&j)dialog('取消演示任务？','<p>停止后续演示，不影响原件条目和已发表资料。正式系统中在途模型请求仍可能计费。</p>',`<button class="btn" data-action="close-dialog">保留任务</button><button class="btn danger" data-action="confirm-cancel" data-id="${id}">确认取消</button>`);
 else if(a==='confirm-cancel'&&j){j.status='cancelled';save();document.querySelector('#dialog').close();render();}
 else if(a==='fix-example'&&j)document.querySelector('#review-text').value=demoTargets[j.language][1];
 else if(a==='save-review'&&j){const t=document.querySelector('#review-text').value.trim();if(!t.includes('64')||t.includes('32')){document.querySelector('#review-error').textContent='示例数字检查未通过：必须保留64，不得出现32。';return;}j.translation=t;j.issue=false;j.status='ready';j.step=5;save();navigate('jobs/'+id);}
 else if(a==='publish'&&j)publishJob(j);
 else if(a==='save-draft'&&d){const t=document.querySelector('#segment-editor').value.trim();if(!t){toast('译文不能为空');return;}d.draft={target:t,version:(d.draft?.version||d.blocks[1].version)+1};save();render();toast('草稿已保存，当前静态版未改动。');}
 else if(a==='candidate'&&d){d.candidate={base:d.draft?.version||d.blocks[1].version,target:demoTargets[d.language][1]};save();render();}
 else if(a==='accept-candidate'&&d&&d.candidate){if(d.candidate.base!==(d.draft?.version||d.blocks[1].version)){toast('候选基准已过期；当前草稿保留，请重新生成候选。');return;}d.draft={target:d.candidate.target,version:d.candidate.base+1};delete d.candidate;save();render();}
 else if(a==='publish-draft'&&d){if(!d.draft){toast('请先保存草稿。');return;}if(!d.draft.target.includes('64')||d.draft.target.includes('32')){toast('保护数字检查失败，未发布。');return;}const blocks=structuredClone(d.blocks);blocks[1].target=d.draft.target;blocks[1].version=d.draft.version;blocks[1].reviewed=false;const next=Math.max(...d.history.map(x=>x.revision))+1;d.history.push({revision:next,blocks:structuredClone(blocks),reason:'人工修改示例，未等同人工确认',time:new Date().toISOString()});d.blocks=blocks;d.revision=next;d.generation++;delete d.draft;delete d.candidate;save();navigate('history/'+id);}
 else if(a==='rollback'&&d){const h=d.history.find(x=>x.revision===Number(b.dataset.revision));if(h){d.blocks=structuredClone(h.blocks);d.revision=h.revision;d.generation++;delete d.draft;delete d.candidate;save();render();}}
 else if(a==='delete-term'){state.glossary=state.glossary.filter(x=>x.id!==id);state.glossaryVersion++;save();render();}
 else if(a==='reset')dialog('恢复原型示例？','<p>只清除此浏览器的演示条目、任务与术语，不删除已下载文件。</p>','<button class="btn" data-action="close-dialog">取消</button><button class="btn danger" data-action="confirm-reset">恢复示例</button>');
 else if(a==='confirm-reset'){state=defaultState();selectedFiles=[];originalFiles.forEach(URL.revokeObjectURL);originalFiles.clear();save();document.querySelector('#dialog').close();navigate('library');render();}
 else if(a==='scope')dialog('原型能力边界','<p><strong>可实际操作：</strong>PDF初筛与浏览器元数据、文档筛选/收藏、原有静态文章阅读/导出、术语偏好、演示样例的编辑/候选/版本回滚。</p><p><strong>未实现：</strong>服务端PDF保存、全文解析、模型翻译、数据库、持久Worker与生产容器。所有任务使用明确标注的固定样例。</p><p>正式规格同样没有登录、团队或权限功能。根目录Compose只托管本原型，生产部署另见契约。</p>');
 else if(a==='close-dialog')document.querySelector('#dialog').close();
});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
render();
