function staticReader(doc){
 const lang=LANGS[doc.language]?doc.language:'zh-Hans';
 const sourceLang=doc.sourceLanguage||'en';
 const title=doc.title;
 const blocks=(doc.blocks||[]).map((b,i)=>`<div class="pair" id="block-${i+1}" data-block-id="${esc(b.id)}"><div class="para en" lang="${esc(sourceLang)}" dir="auto"><span class="label">原文</span>${esc(b.source)}</div><div class="para zh" lang="${esc(lang)}" dir="auto"><span class="label">${esc(LANGS[lang])}</span>${esc(b.target)}</div></div>`).join('\n');
 const script=`(()=>{const r=document.documentElement,b=document.body;const get=k=>{try{return localStorage.getItem(k)}catch{return null}},set=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};const mode=m=>{b.dataset.language=m;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.mode===m)));set('reader-view',m)};const old=get('reader-view');if(['both','en','zh'].includes(old))mode(old);r.dataset.theme=get('reader-theme')||'light';let size=Math.min(25,Math.max(14,Number(get('reader-size'))||18));r.style.setProperty('--font-size',size+'px');document.querySelectorAll('[data-mode]').forEach(x=>x.onclick=()=>mode(x.dataset.mode));document.querySelector('[data-theme-toggle]').onclick=()=>{r.dataset.theme=r.dataset.theme==='dark'?'light':'dark';set('reader-theme',r.dataset.theme)};document.querySelectorAll('[data-size]').forEach(x=>x.onclick=()=>{size=Math.min(25,Math.max(14,size+Number(x.dataset.size)));r.style.setProperty('--font-size',size+'px');set('reader-size',String(size))});window.addEventListener('scroll',()=>{let total=document.documentElement.scrollHeight-innerHeight;document.querySelector('.progress').style.width=(total>0?scrollY/total*100:100)+'%'},{passive:true});document.querySelector('[data-print]').onclick=()=>print();})();`;
 return `<!doctype html><html lang="zh-CN" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="generator" content="bilingual-library reader-v1 prototype"><meta name="referrer" content="no-referrer"><title>${esc(doc.title)} · 双语阅读</title><style>${READER_CSS}\n.para{white-space:pre-wrap;overflow-wrap:anywhere;text-align:start}.hero h1{overflow-wrap:anywhere}.para[lang=ar]{font-family:system-ui,sans-serif}.source-disclosure{font-size:13px}</style></head><body data-language="both"><div class="progress" aria-hidden="true"></div><nav class="toolbar" aria-label="阅读设置"><button data-mode="both" aria-pressed="true">原文与译文</button><button data-mode="zh" aria-pressed="false">仅译文</button><button data-mode="en" aria-pressed="false">仅原文</button><button data-size="-1" aria-label="减小字号">A−</button><button data-size="1" aria-label="增大字号">A+</button><button data-theme-toggle>明 / 暗</button><button data-print>打印</button></nav><header class="hero"><div class="kicker">Bilingual document · 双语逐段对照</div><h1>${esc(title)}</h1>${false?'':`<p class="original-title">${esc(doc.title)}</p>`}<p class="meta">${esc(LANGS[lang])} · ${doc.blocks.length} 组段落 · reader-v1 · 修订 ${Number(doc.revision)||1}</p><div class="note"><strong>版本说明：</strong>${esc(doc.note||'固定流程样例，不是上传PDF的翻译；未连接真实服务。')}</div></header><div class="layout"><aside class="toc"><h2>内容 / Contents</h2>${doc.blocks.map((b,i)=>`<a href="#block-${i+1}">第 ${i+1} 段 · ${esc(b.source.slice(0,24))}${b.source.length>24?'…':''}</a>`).join('')}</aside><article><section class="section-heading"><h2><span class="en-title">Original &amp; translation</span><span class="zh-title">原文与译文</span></h2></section>${blocks}</article></div><footer class="footer">静态阅读副本 · 所有正文已经写入 HTML · 不需要翻译服务、数据库或外部资源。此副本没有远程撤回能力。</footer><script>${script}</script></body></html>`;
}
function downloadBlob(filename,content,type='text/html;charset=utf-8'){
 const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);
}
function exportDoc(doc){
 if(doc.kind==='legacy'){const a=document.createElement('a');a.href='exports/'+doc.filename;a.download=doc.filename;document.body.append(a);a.click();a.remove();toast('导出单文件 HTML；图片已嵌入，不包含原始 PDF。');}
 else{downloadBlob('bilingual-'+doc.id+'.html',staticReader(doc));toast('静态 HTML 已生成；正文无需 JavaScript 即可阅读。');}
}
